services:
  webscraper:
    build:
      context: ./app
    container_name: webscraper
    volumes:
      - ./app:/usr/src/app
    develop:
      watch:
        - path: ./app/requirements.txt
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync+restart
    command: tail -f /dev/null
  selenium-hub:
    image: "selenium/hub:3.141.59"
    container_name: selenium-hub
    ports:
      - "4444:4444"
  # redis:
  #   image: "redis:alpine"
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - "6379:6379"

volumes:
  # redis_data:
  app:
