services:
  scraper:
    build:
      context: .
      dockerfile: ./docker/scripts/Dockerfile
    container_name: scraper
    volumes:
      - .:/usr/src/app
    command:
      - tail
      - -f
      - /dev/null
volumes:
  app:
