name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Docker compose up
        run: docker compose -f app/docker-compose.yaml up -d
      - name: Start main.py
        run: docker exec -it webscraper python main.py
      - name: Docker compose down
        run: docker compose -f app/docker-compose.yaml down
